/// 이모지와 아이콘 코드 매핑을 관리하는 상수 클래스
class EmojiConstants {
  // 이모지를 아이콘 코드로 매핑
  static const Map<String, String> emojiToIconCode = {
    '😀': 'SMILE',
    '😃': 'HAPPY',
    '😄': 'JOY',
    '😁': 'GRIN',
    '😆': 'LAUGH',
    '😅': 'SWEAT',
    '😂': 'CRY_LAUGH',
    '🤣': 'ROFL',
    '🥲': 'TEAR_JOY',
    '☺️': 'BLUSH',
    '😊': 'HAPPY_EYES',
    '🙂': 'SLIGHT_SMILE',
    '😍': 'HEART_EYES',
    '🥰': 'LOVE',
    '😘': 'KISS',
    '😙': 'KISS_SMILE',
    '😚': 'KISS_EYES',
    '😋': 'YUM',
    '😝': 'TONGUE',
    '🤨': 'RAISED_EYEBROW',
    '🤓': 'NERD',
    '😎': 'COOL',
    '😏': 'SMIRK',
    '🥳': 'PARTY',
    '😟': 'WORRIED',
    '😖': 'CONFOUNDED',
    '😫': 'TIRED',
    '🥺': 'PLEADING',
    '😡': 'ANGRY',
    '🤒': 'SICK',
    '😱': 'SCREAM',
    '😪': 'SLEEPY',
    '😮': 'SURPRISE',
    '👍': 'THUMBS_UP',
    '👎': 'THUMBS_DOWN',
    '🙏': 'PRAY',
    '⚽': 'SOCCER',
    '🎨': 'ART',
    '🎟️': 'TICKET',
    '🧩': 'PUZZLE',
    '🎤': 'MIC',
    '🎬': 'MOVIE',
    '🖥️': 'COMPUTER',
    '💡': 'IDEA',
    '⏰': 'ALARM',
    '💊': 'PILL',
    '🛁': 'BATH',
    '🧻': 'TISSUE',
    '🚴‍♂️': 'BIKE',
    '🎮': 'GAME',
    '🍎': 'APPLE',
    '🥗': 'SALAD',
    '❤️': 'HEART',
    '💣': 'BOMB',
    '🎉': 'PARTY_POPPER',
    '🍀': 'CLOVER',
    '🌙': 'MOON',
    '🐶': 'DOG',
    '💪': 'MUSCLE',
    '🎾': 'TENNIS',
    '🏃': 'RUN',
    '🚩': 'FLAG',
    '🧶': 'YARN',
    '🔥': 'FIRE',
    '💼': 'BRIEFCASE',
    '🍽️': 'DINNER',
    '☕': 'COFFEE',
    '🪥': 'TOOTHBRUSH',
    '🚗': 'CAR',
    '🏥': 'HOSPITAL',
    '📱': 'PHONE',
    '📝': 'NOTE',
    '📅': 'CALENDAR',
  };

  // 아이콘 코드를 이모지로 매핑 (역방향 매핑)
  static const Map<String, String> iconCodeToEmoji = {
    'SMILE': '😀',
    'HAPPY': '😃',
    'JOY': '😄',
    'GRIN': '😁',
    'LAUGH': '😆',
    'SWEAT': '😅',
    'CRY_LAUGH': '😂',
    'ROFL': '🤣',
    'TEAR_JOY': '🥲',
    'BLUSH': '☺️',
    'HAPPY_EYES': '😊',
    'SLIGHT_SMILE': '🙂',
    'HEART_EYES': '😍',
    'LOVE': '🥰',
    'KISS': '😘',
    'KISS_SMILE': '😙',
    'KISS_EYES': '😚',
    'YUM': '😋',
    'TONGUE': '😝',
    'RAISED_EYEBROW': '🤨',
    'NERD': '🤓',
    'COOL': '😎',
    'SMIRK': '😏',
    'PARTY': '🥳',
    'WORRIED': '😟',
    'CONFOUNDED': '😖',
    'TIRED': '😫',
    'PLEADING': '🥺',
    'ANGRY': '😡',
    'SICK': '🤒',
    'MELT': '😄',
    'SCREAM': '😱',
    'SLEEPY': '😪',
    'SURPRISE': '😮',
    'THUMBS_UP': '👍',
    'THUMBS_DOWN': '👎',
    'PRAY': '🙏',
    'SOCCER': '⚽',
    'ART': '🎨',
    'TICKET': '🎟️',
    'PUZZLE': '🧩',
    'MIC': '🎤',
    'MOVIE': '🎬',
    'COMPUTER': '🖥️',
    'IDEA': '💡',
    'ALARM': '⏰',
    'PILL': '💊',
    'BATH': '🛁',
    'TISSUE': '🧻',
    'BIKE': '🚴‍♂️',
    'GAME': '🎮',
    'APPLE': '🍎',
    'SALAD': '🥗',
    'HEART': '❤️',
    'BOMB': '💣',
    'PARTY_POPPER': '🎉',
    'CLOVER': '🍀',
    'MOON': '🌙',
    'DOG': '🐶',
    'MUSCLE': '💪',
    'TENNIS': '🎾',
    'RUN': '🏃',
    'FLAG': '🚩',
    'YARN': '🧶',
    'FIRE': '🔥',
    'BRIEFCASE': '💼',
    'DINNER': '🍽️',
    'COFFEE': '☕',
    'TOOTHBRUSH': '🪥',
    'CAR': '🚗',
    'HOSPITAL': '🏥',
    'PHONE': '📱',
    'NOTE': '📝',
    'CALENDAR': '📅',
  };

  // 이모지 목록 (UI에서 선택 가능한 이모지들)
  static const List<String> availableEmojis = [
    '😀',
    '😃',
    '😄',
    '😁',
    '😆',
    '😅',
    '😂',
    '🤣',
    '🥲',
    '☺️',
    '😊',
    '🙂',
    '😍',
    '🥰',
    '😘',
    '😙',
    '😚',
    '😋',
    '😝',
    '🤨',
    '🤓',
    '😎',
    '😏',
    '🥳',
    '😟',
    '😖',
    '😫',
    '🥺',
    '😡',
    '🤒',
    '😱',
    '😪',
    '😮',
    '👍',
    '👎',
    '🙏',
    '⚽',
    '🎨',
    '🎟️',
    '🧩',
    '🎤',
    '🎬',
    '🖥️',
    '💡',
    '⏰',
    '💊',
    '🛁',
    '🧻',
    '🚴‍♂️',
    '🎮',
    '🍎',
    '🥗',
    '❤️',
    '💣',
    '🎉',
    '🍀',
    '🌙',
    '🐶',
    '💪',
    '🎾',
    '🏃',
    '🚩',
    '🧶',
    '🔥',
    '💼',
    '🍽️',
    '☕',
    '🪥',
    '🚗',
    '🏥',
    '📱',
    '📝',
    '📅',
  ];

  // 기본 이모지
  static const String defaultEmoji = '😊';
  static const String defaultIconCode = 'HAPPY_EYES';

  // 캘린더 기본 이모지
  static const String calendarDefaultEmoji = '📅';
  static const String calendarDefaultIconCode = 'CALENDAR';

  /// 이모지를 아이콘 코드로 변환
  static String convertEmojiToIconCode(String? emoji) {
    if (emoji == null || emoji.isEmpty) return defaultIconCode;
    return emojiToIconCode[emoji] ?? defaultIconCode;
  }

  /// 아이콘 코드를 이모지로 변환
  static String convertIconCodeToEmoji(String? iconCode) {
    if (iconCode == null || iconCode.isEmpty) return defaultEmoji;

    // 이미 이모지인 경우 그대로 반환
    if (iconCode.contains(RegExp(r'[^\x00-\x7F]'))) {
      return iconCode;
    }

    return iconCodeToEmoji[iconCode] ?? defaultEmoji;
  }
}
